version: '3'

services:
    web:
        image: nginx:latest
        ports:
            - 8080:8080
        volumes:
            - ./www:/www
            - ./site.conf:/etc/nginx/conf.d/site.conf
        links:
            - php
    php:
        image: php:7-fpm
        volumes:
            - ./www:/www